import Head from 'next/head'
import PageLayout from '../components/PageLayout'
import Navbar from '../components/Navbar'
import Sidemenu from '../components/Sidemenu'
import Content from '../components/motion/Content'

const motion = () => {
  return (
    <>
      <Head>
        <title>Motion Guideline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout
        sidemenu={<Sidemenu />}
        nav={<Navbar />}
        main={<Content />} />
    </>
  )
}

export default motion